package com.healthlysavings.api.domain;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
/**
 * Created by jrdavis on 3/14/16.
 */
@Entity
@Table(name = "users")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's email
    @NotNull
    private String email;

    // The user's name
    @NotNull
    private String first_name;

    // The user's address
    @NotNull
    private String userAddress;

    // The user's Gender
    @NotNull
    private String userGender;

    // The user's height
    @NotNull
    private Double userHeight;

    // The user's Weight
    @NotNull
    private Double userWeight;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public User() { }

    public User(long id) {
        this.id = id;
    }



    public User(String email, String first_name, String userAddress, String userGender, Double userHeight, Double userWeight) {
        this.email = email;
        this.first_name = first_name;
        this.userAddress = userAddress;
        this.userGender = userGender;
        this.userHeight = userHeight;
        this.userWeight = userWeight;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getFirstName() {
        return first_name;
    }

    public void setName(String value) {
        this.first_name = value;
    }
    public String getUserAddress() {
        return userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getUserGender() {
        return userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    public Double getUserHeight() {
        return userHeight;
    }

    public void setUserHeight(Double userHeight) {
        this.userHeight = userHeight;
    }

    public Double getUserWeight() {
        return userWeight;
    }

    public void setUserWeight(Double userWeight) {
        this.userWeight = userWeight;
    }


}